### ISSUE TITLE
希望可以临时加入tag

### ISSUE THREAD

**Issue by ysmintor** [pengwei1024/LogUtils#11]
比如orhanobut的logger支持临时.t('TAG‘),有时候还是需要加以区分的。另外在打印普通的地方不知道为什么没有显示外边框。只在打印json才显示，但我已经开启了。

**Comment by pengwei1024** [comment]
感谢反馈，我这边会排查一下不显示边框可能的原因，json默认走Log.d。设置tag的话会在以后版本推出

**Comment by pengwei1024** [comment]
1.4.0版本已经加入设置tag功能，不输出边框的原因暂时没找到，你能提供更多的信息吗？ @ysmintor

**Comment by ysmintor** [comment]
@pengwei1024 更新设置后好像不输出边框的原因已经解决了，可能是我这边加载的问题。

另外和logger相比，您的这个LogUtils没有显示进程是什么原因？是默认关闭的吗？

**Comment by pengwei1024** [comment]
LogUtils没有提供显示线程信息的功能，开发中一般就主线程和各种子线程，我觉得输出线程名称意义不大，让开发者用Thread.currentThread().getName()输出线程名可以更灵活。你在开发中需要知道当前日志的线程名？

**Comment by ysmintor** [comment]
好的，明白了。开发中不太需要这个功能，但有时在调试的时候一目了然，特别是网络异步引起的问题。之前我使用的是logger，页楼主这个直接显示list或者intent内容，方便不少，真是大赞！！

**Comment by pengwei1024** [comment]
@ysmintor 谢谢支持，我会一直优化下去的，也希望你们能提供更好建议去完善这个库。

**Comment by pengwei1024** [comment]
@ysmintor 1.4.2版本支持个性化设置Tag了，configFormatTag("%c{-5} %t") 就可以显示出当前线程名称了
