### ISSUE TITLE
在lambda表达式中，出现打印不出日志的问题

### ISSUE THREAD

**Issue by duckAndroid** [pengwei1024/LogUtils#12]
如题。另外，还有一个小问题，就是在lambda表达式中，有时候出现，可以打印行号和内容，但是不能定位

**Comment by pengwei1024** [comment]
能详细说明下你的使用场景吗？我这边测试简单的lambda没问题。
```java
TextView tv = (TextView) findViewById(R.id.tv_test);
 tv.setOnClickListener(v -> LogUtils.d("test lambda!"));
```

**Comment by lengyue524** [comment]
@pengwei1024 他的问题应该是tag太长导致的问题，我今天提交了pull request是解决这个问题的。你看看是否有问题，没问题就合并了吧

**Comment by lengyue524** [comment]
@duckAndroid 你可以使用我fork分支试试，在 @pengwei1024 解决前代替一下
`
compile 'com.github.lengyue524:LogUtils:1.4.3'
`
