### ISSUE TITLE
1.4.2版本用compile导入，出现找不到包的错误

### ISSUE THREAD

**Issue by lujianzhao** [pengwei1024/LogUtils#13]
请问下compile 'com.apkfuns.logutils:library:1.4.2' 为什么导入不了这个项目呢？

**Comment by pengwei1024** [comment]
应该不会呀，http://jcenter.bintray.com/com/apkfuns/logutils/library/ 能看到已经上传成功，你是不是本地开启了离线功能？build>build tools>Gradle>Offline work。或者换个网络试试？
