### ISSUE TITLE
性能问题

### ISSUE THREAD

**Issue by TonyTangAndroid** [pengwei1024/LogUtils#21]
我为了不影响release 版本的效率，我通过config 把log关闭，然后再使用hugo 简单做了一下性能测试，发现即使关闭了log，它还会去判断 该怎么打印 log，这会花费很多时间。我在MainActivity里，onCreate一共花费了140ms，但是132ms是耗费在log里。这里可以做一做优化。

具体 测试 代码 请参考 我的 pull request 

https://github.com/pengwei1024/LogUtils/pull/20

**Comment by pengwei1024** [comment]
非常感谢你提交代码。本地为了测试用了System.out.println()， 所以导致有点慢，我在本地尝试提供一份release no-op版本，先看看这样效果明不明显。

**Comment by TonyTangAndroid** [comment]
谢谢你的开源库。这是github里打印日志最强大的库，除了在这里提及的性能问题之外。

**Comment by pengwei1024** [comment]
@TonyTangAndroid 现在提供了release-no-op版本，尽可能对线上不造成性能影响，欢迎试用。
```groovy
debugCompile 'com.apkfuns.logutils:library:1.4.2'
releaseCompile 'com.apkfuns.logutils:logutils-no-op:1.4.2.1'
```
