### ISSUE TITLE
【咨询】日志打印加边框

### ISSUE THREAD

**Issue by JerrryLiu** [pengwei1024/LogUtils#22]
为了更加方便观看日志打印，需要添加边框，需要怎样配置？
![image](https://cloud.githubusercontent.com/assets/7981299/17048873/d187d4ce-501b-11e6-8735-a13249a2c5dc.png)

**Comment by JerrryLiu** [comment]
类似Logger框架的打印
![image](https://cloud.githubusercontent.com/assets/7981299/17049070/72d2d738-501d-11e6-9e6f-d601eb225c41.png)

**Comment by JerrryLiu** [comment]
@pengwei1024

**Comment by JerrryLiu** [comment]
已经弄出来了，但在android studio中查看日志打印格式乱了
![image](https://cloud.githubusercontent.com/assets/7981299/17051416/33fd6146-502b-11e6-8781-3cf77ab670ee.png)

**Comment by JerrryLiu** [comment]
尝试点击android studio logcat 面板中各种按钮，最后给整出来了！
LogUtils 实在是太NB了，居然可以直接打印对象！！！
感谢！！！

![image](https://cloud.githubusercontent.com/assets/7981299/17051665/699fedd6-502c-11e6-844f-139752f83dea.png)

**Comment by pengwei1024** [comment]
这是你自己写的边界线吗？ LogUtils可以设置出现或者隐藏边界线
```java
LogUtils.getLogConfig().configShowBorders(true)
```

**Comment by MIkeeJY** [comment]
LogUtils.getLogConfig()
                    .configAllowLog(BuildConfig.DEBUG)
                    .configTagPrefix(this.getPackageName())
                    .configShowBorders(true)
                    .configFormatTag("%d{HH:mm:ss:SSS} %t %c{-5}")
                    .configLevel(LogLevel.TYPE_VERBOSE)
            ;

**Comment by Lnybb** [comment]
提问者一边咨询一边自问自答，哈哈，可以
