### ISSUE TITLE
不知道为什么有时候打印不出来日志

### ISSUE THREAD

**Issue by Lnybb** [pengwei1024/LogUtils#23]
环境如下
`
compile 'com.apkfuns.logutils:library:1.4.2'

public class App extends Application {
    private static App mApp;

    public static App getInstance() {
        return mApp;
    }

    @Override
    public void onCreate() {
        super.onCreate();
        mApp = this;
        setupLogUtils();
    }

    private void setupLogUtils() {
        LogUtils.getLogConfig()
                .configAllowLog(true)
                .configTagPrefix("zyd")
                .configShowBorders(true)
                .configLevel(LogLevel.TYPE_VERBOSE);
    }
}

public class MainController extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main_controller);
        Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);
        LogUtils.d("");
    }

    @OnClick(R.id.bn)
    public void testFunction() {
        LogUtils.d("");
        func1();
    }

    private void func1() {
        String[] names = {"aa", "bb", "cc"};
        Observable
                .from(names)
                .subscribe(new Action1<String>() {
                    @Override
                    public void call(String s) {
                        LogUtils.d(s);
                    }
                });
    }
}
`

**Comment by pengwei1024** [comment]
是用了Rxjava的不显示还是所有LogUtils的都不显示？或者说所有系统日志都不显示？

**Comment by Lnybb** [comment]
所有都不显示，系统日志可以显示
这是点击button后显示的日志，日志级别Debug
`
com.zh.pratice D/FeatureProxyBase: FeatureProxyBase class constructor
com.zh.pratice D/MultiWindow: MultiWindowProxy constructor.
com.zh.pratice D/FeatureProxyBase: getService(), serviceName = multiwindow_service_v1
com.zh.pratice D/Surface: Surface::setBuffersDimensions(this=0x7f89e3aa00,w=1080,h=1920)
`

**Comment by Lnybb** [comment]
犯了个弱智错误。。。
使用ButterKnife忘了绑定布局。。。
现在又能打印了。。。
