### ISSUE TITLE
准确显示调用方法、行，是否可以支持动态设置methodCount

### ISSUE THREAD

**Issue by imliujun** [pengwei1024/LogUtils#24]
从Logger转到LogUtils，用了一段时间感觉LogUtils比较符合使用习惯，但是能否支持类似于Logger的methodCount，methodOffset方法，因为有些log打印在公共的方法中，LogUtils默认只打印当前方法名和代码行数，不太方便定位到调用此方法的代码位置。
如果能够提供类似
LogUtils.methodCount(2).methodOffset(1).d("我是打印内容");
形式的调用方式就更好了。

**Comment by pengwei1024** [comment]
谢谢反馈和支持，近期我会调研一下的

**Comment by imliujun** [comment]
configMethodOffset方法如果能够像tag一样每次打印都可以设置临时的值就好了
