### ISSUE TITLE
对比原生log，性能下降明显

### ISSUE THREAD

**Issue by appsbuilder999** [pengwei1024/LogUtils#29]
使用demo中的配置，打印hello world 3000次，原生的只需要40ms，LogUtils需要6000ms，虽然是方便了不少，担心在大型项目上性能损失严重，有优化的可能不？

**Comment by pengwei1024** [comment]
感谢你的建议，我会考虑进行性能优化的。因为这个库是基于原生Log库的封装，而且打印对象的时候部分使用了反射，速度比Log慢是肯定的。我开发这个库的初衷是利于debug，更快捷的打印List，Map，Intent等对象，线上建议使用releaseCompile no-op版本，或者关闭日志输出，这样线上损耗基本上就可以忽略了。debug的话有点性能损耗影响也不大，还是要方便开发为主，你觉得呢？
