### ISSUE TITLE
部分情况下 会导致 format 失败

### ISSUE THREAD

**Issue by JuneLeGency** [pengwei1024/LogUtils#3]
https://github.com/pengwei1024/LogUtils/blob/547475a757fbe1ff5fb7537694a3d0ed1ea5d627/library/src/main/java/com/apkfuns/logutils/Logger.java#L52

应该需要做一些格式化前的预处理操作
否则会报
java.util.MissingFormatArgumentException: Format specifier: 5B

**Comment by JuneLeGency** [comment]
一般都是打URL 这种log 时候 被encode 出现%* 的东西

**Comment by JuneLeGency** [comment]
1.0.6已修复

**Comment by pengwei1024** [comment]
感谢你的支持(*^__^*)
