### ISSUE TITLE
打印类名方法名的问题

### ISSUE THREAD

**Issue by tree1224** [pengwei1024/LogUtils#30]
你好，我在使用LogUtils的时候封装了一层，这样方便统一替换或修改log工具，但这时候打印的类名和方法名就是封装的log class的类名和方法名，能否加一个配置项，设定在backtrace中找到正确的类名和方法名以及文件和行数

**Comment by pengwei1024** [comment]
新版本已经支持configMethodOffset方法，欢迎试用
