### ISSUE TITLE
Android7.0能用吗，感觉你的外部存储应该会出问题

### ISSUE THREAD

**Issue by 354420603** [pengwei1024/LogUtils#32]

**Comment by pengwei1024** [comment]
我拿4.0 - 7.0 的手机都试过了没问题呀，为什么觉得有问题？

**Comment by 354420603** [comment]
7.0还能拿到外部的存储路径吗

**Comment by 354420603** [comment]
还没是配过7.0

**Comment by pengwei1024** [comment]
突然发现我demo targetSdkVersion 用的22， 确实有问题，多谢反馈

**Comment by pengwei1024** [comment]
@354420603 我觉得SDK就不该做权限申请的事，其他日志库都没有处理权限。请问你有什么更好的建议或者处理方式吗？

**Comment by 354420603** [comment]
那就不做保存日志的处理了，平时我是没用到过的！我懂得不多，很尴尬

**Comment by 354420603** [comment]
而且我看了下7.0的存储到外部SD卡貌似是要在manifest声明

**Comment by 354420603** [comment]
我有个建议，能不能有一个方法可以设置只有在debug模式下才打印log

**Comment by pengwei1024** [comment]
有啊。LogUtils.getLogConfig().configAllowLog(isDebug), 是否输入文件用LogUtils.getLog2FileConfig().configLog2FileEnable(isDebug)

**Comment by 354420603** [comment]
sorry我没仔细看

**Comment by 354420603** [comment]
最近在看rxjava，结合一下会不会让打印的对应用性能的影响小一点

**Comment by 354420603** [comment]
感觉rx很强大

**Comment by pengwei1024** [comment]
rx主要是链式调用和更方便切换线程，对性能应该没啥影响。为了尽量减少影响，建议release用no-op版本
```
debugCompile 'com.apkfuns.logutils:library:1.5.1'
releaseCompile 'com.apkfuns.logutils:logutils-no-op:1.5.1'
```
