### ISSUE TITLE
log2file的一些异常信息

### ISSUE THREAD

**Issue by imliujun** [pengwei1024/LogUtils#34]
![image](https://cloud.githubusercontent.com/assets/9779970/25031880/6d7ac776-2102-11e7-8e8d-78fe237b9727.png)

**Comment by imliujun** [comment]
还是这个异常
`java.lang.IllegalArgumentException:Log2FilePath is an invalid path`
但是奇怪的地方在于，我观察这个异常不是在初始化的时候报的，用户使用了51 秒后才报，并且在这之前用户已经在同一个

**Comment by imliujun** [comment]
java.lang.IllegalArgumentException:Log2FilePath is an invalid path

这个异常出现的时机我感觉有问题，我发现在程序运行中也有很多这个异常信息，首先程序启动的时候肯定设置了FilePath，并且启动的时候就打印了log，如果FilePath不可用应该直接启动就崩溃才对，为什么会运行一段时间后才报出这个异常？FilePath应该不会在使用中被回收吧

**Comment by imliujun** [comment]
![image](https://cloud.githubusercontent.com/assets/9779970/25035679/992aebde-2121-11e7-841d-d976b4f4ce4e.png)

**Comment by imliujun** [comment]
![image](https://cloud.githubusercontent.com/assets/9779970/25035728/d4fa04e2-2121-11e7-9700-f1810a3c6415.png)

**Comment by pengwei1024** [comment]
FilePath是保存在一个单例里面，按道理来说应该是不会回收的。好多异常啊，我会把写日志再优化下的

**Comment by imliujun** [comment]
初始化filePath的时候还遇到这种奇葩问题，无言以对了
![image](https://cloud.githubusercontent.com/assets/9779970/25035923/3b04e120-2123-11e7-8016-1f2a382458fe.png)
