### ISSUE TITLE
打印日记时的BUG

### ISSUE THREAD

**Issue by lujianzhao** [pengwei1024/LogUtils#35]
当打印的string长度超过3072时，会导致.tag设置的tag无效，采用的tag是默认的tag..比如：
 LogUtils.getLogConfig().configAllowLog(isDebug()).configTagPrefix("Test"); //初始化LogUtils
LogUtils.tag("Response").w(bodyString); //当bodyString的长度超过3072时，打印的TAG是"Test";长度3072以下时，打印的TAG是"Response"。

**Comment by pengwei1024** [comment]
多谢反馈，我会尽快修复的
