### ISSUE TITLE
源码怎么导出Jar包

### ISSUE THREAD

**Issue by JerrryLiu** [pengwei1024/LogUtils#37]
需要更改些源码，使其更加匹配自己的想要的打印，但怎么导出Jar包呢？

**Comment by pengwei1024** [comment]
@JerrryLiu 直接运行，在library项目 build/intermediates/bundles/release/ 文件夹下会产生一个classes.jar , 就是你需要的jar包

**Comment by pengwei1024** [comment]
或者你直接执行./gradlew build就行，我已经写好了gradle 脚本
```
build << {
    def jarName = "logutil-$android.defaultConfig.versionName\\.jar"
    copy {
        from('build/intermediates/bundles/release/')
        into("$rootDir/jar/")
        include('classes.jar')
        rename('classes.jar', jarName)
    }
}
```

**Comment by JerrryLiu** [comment]
直接运行library项目，但没有build/intermediates/bundles/release/ 文件夹，只有debug与default文件夹
![image](https://cloud.githubusercontent.com/assets/7981299/25899713/7967bd20-35c3-11e7-9064-8a7716db384a.png)

**Comment by JerrryLiu** [comment]
难道是debug目录中的class.jar 文件？

**Comment by pengwei1024** [comment]
因为没混淆和其他额外操作，所以release 和 debug 其实是一样的，你把jar改个名字就好了

**Comment by JerrryLiu** [comment]
好的，谢谢！！！
