### ISSUE TITLE
作者知道为什么用JReble编译后LogUtils打印不出来吗

### ISSUE THREAD

**Issue by NathanXuns** [pengwei1024/LogUtils#39]
我发现用JRebel编译后LogUtils就打印不出来，切换到正常studio的Instant Run编译后一切就正常了。

**Comment by MIkeeJY** [comment]
@NathanXuns 你用的是最新版的jrebel？

**Comment by NathanXuns** [comment]
嗯，使用最新的没有问题了
MIkeeJY <notifications@github.com>于2017年7月6日 周四20:40写道：
