### ISSUE TITLE
在Android studio3.1版本上打印时有点乱。

### ISSUE THREAD

**Issue by lujianzhao** [pengwei1024/LogUtils#46]
在Android studio3.1版本上打印时有点乱。日记的边框没对齐。

**Comment by pengwei1024** [comment]
Android Studio 3.1版本date、pid、package、Tag这四个参数相同的日志就会合并只显示一次，而且新版本会强制换行，之前的制表符结构已经不好展示了，我正在考虑新的清晰的打印结构，所以时间发版时间会稍微长一点

**Comment by pengwei1024** [comment]
<img width="352" alt="machi 2018-03-29 23-09-39" src="https://user-images.githubusercontent.com/10805586/38096829-6eff3d72-33a6-11e8-8b9e-a62c584e9b12.png"> 你暂时可以先关了其他输出这样看会稍微舒服点

**Comment by lujianzhao** [comment]
非常感谢，我去关闭试试

**Comment by yuxingfafu** [comment]
楼主gradle依赖貌似不行的呀？是我网络有问题还是？
   implementation 'com.apkfuns.logutils:library:1.6.0'
implementation 'com.apkfuns.log2file:log2file:1.1.0'  昨天还可以，今天就不行了，是我的网络出问题了？

**Comment by pengwei1024** [comment]
@yuxingfafu 文件改成了由mmap实现，在日志量达到4k或者重新启动后才会写到文件。频繁写日志性能损耗比较高

**Comment by yuxingfafu** [comment]
要重启设备？还是重启应用？才会写到文件是么？

**Comment by pengwei1024** [comment]
重启应用。或者执行`LogUtils.getLog2FileConfig().flushAsync()`也会马上写入。如果希望日志立即写入文件，可以用 `implementation 'com.apkfuns.log2file:log2file:1.0.0'  1.0版本的，那个没有使用mmap，当然1.1.0版本性能更好

`

**Comment by MIkeeJY** [comment]
什么时候发布新版本？

**Comment by pengwei1024** [comment]
@MIkeeJY 我争取这周末发一版解决这个问题

**Comment by pengwei1024** [comment]
@MIkeeJY 已经发布1.6.1版本，欢迎试用
