### ISSUE TITLE
修改MethodOffset之后，可能导致崩溃，建议增加一个最大值判断

### ISSUE THREAD

**Issue by sunsteam** [pengwei1024/LogUtils#48]
### 修改MethodOffset之后，可能导致崩溃，建议增加一个最大值判断。另外，打印Activity这种复杂对象的时候会导致栈溢出，虽然使用时可以注意，但是如果能代码控制边界更好

---

![image](https://user-images.githubusercontent.com/7489390/40834119-896f2f84-65c2-11e8-965d-f5fe89567cde.png)

**Comment by pengwei1024** [comment]
多谢反馈后续会逐渐完善

**Comment by pengwei1024** [comment]
1.6.0版本已经解决
