### ISSUE TITLE
开始写入log到本地文件后，删除文件，如果不重启app，后续就不会生成文件继续写入内容了

### ISSUE THREAD

**Issue by sunsteam** [pengwei1024/LogUtils#49]
Buffer建立后，没有判断file非空但非exist的情况，导致这个问题

顺便问一下，能否给一个具体点的更新计划？ 一是挺久没更新了，积攒了一些问题。二是问题定位不麻烦，只是做修复性更新，看活动情况也一直有提交别的项目代码，这个项目能否插插队修复一下？

**Comment by pengwei1024** [comment]
这周内会发布新版本的，写入文件日志我本地已经重新改造了，改成了基于[xlog](https://github.com/Tencent/mars) 目前这种性能不太好

**Comment by pengwei1024** [comment]
@sunsteam 已经升级，欢迎试用。

```
implementation 'com.apkfuns.logutils:library:1.6.0'
implementation 'com.apkfuns.log2file:log2file:1.1.0'
```
