### ISSUE TITLE
打印超长字符串时候的bug

### ISSUE THREAD

**Issue by TianGuisen** [pengwei1024/LogUtils#50]
1.5.1版本
如果设置了默认的tag
LogUtils.getLogConfig() .configTagPrefix("aaa")//日志log的前缀	
在打印超长json的时候会分段,如果不使用默认的tag,而是类似这样写LogUtils.d("bbb",json).
只有第一部分的tag是bbb,其他几段的tag都是aaa.

**Comment by pengwei1024** [comment]
多谢反馈会尽快修复
