### ISSUE TITLE
关于替换自己项目中的Logutils问题

### ISSUE THREAD

**Issue by fafala** [pengwei1024/LogUtils#51]
您好，我在自己项目中封装了个基本的Log打印工具，其他地方都是调用该工具类打印的，现在换成您的log框架，我只改动了我原来Log工具类中的，i,e,等方法，只是简单的替换，比如原本是，ELogs.i(..)，现在替换成您的  LogUtils.i(...);然后出现了个问题，打印行号只能打印我原来Log工具类中的行号，无法具体到调用者，这个是无法实现的吗？

**Comment by pengwei1024** [comment]
可以啊，提供了一个方法设置偏移 `configMethodOffset `, 设置成1就好了
