### ISSUE TITLE
Junk in log filenames

### ISSUE THREAD

**Issue by HraD** [pengwei1024/LogUtils#56]
I want to create log files, as in example shown:

```
 LogUtils.getLog2FileConfig().configLog2FileEnable(true)
                            // targetSdkVersion >= 23 需要确保有写sdcard权限
                            .configLog2FilePath(Environment.getExternalStorageDirectory().getPath() + File.separator + "LWN_logs/")
                            .configLog2FileNameFormat("%d{ddMMyyyy}.log")
                            .configLogFileEngine(new LogFileEngineFactory(context));
```

Problem is that filenames contains junk symbols after extention and even can not be deleted.

![screenshot_2018-12-29-13-30-07-0801631188](https://user-images.githubusercontent.com/14878643/50537261-75ab9d00-0b6e-11e9-803a-7a71402eb8dc.png)

When i set filename as
`configLog2FileNameFormat("log.log")`
filename is as expected.

How can i fix it?

**Comment by pengwei1024** [comment]
I'm sorry for this, what brand is your mobile phone?  and what is your system language?  It's hard for me to repeat this problem， I may need more information， I guess it might be related to `String.format` or `date.format`

**Comment by HraD** [comment]
Hi! Lenovo Z5 Android 8.1, Russian Language.

**Comment by HraD** [comment]
Btw, i have root, so can send you logs from logcat and etc...

**Comment by HraD** [comment]
I have tried this code
`.configLog2FileNameFormat(new SimpleDateFormat("ddMMyyyy", Locale.getDefault()).format(new Date()) + ".log")`
but again got junk symbols.

**Comment by tomato0127** [comment]
I have the same problem！！！
老哥，我也有同样的问题，我的是android 4.3.0版本的系统，rk3188 平台，应该是JNI层处理文件名的时候出现的错误。麻烦检查一下。
