### ISSUE TITLE
打包的时候报错  com.apkfuns.logutils.Constant: can't find referenced method 'java.util.List getParseList()' in program class com.apkfuns.logutils.LogConfigImpl

### ISSUE THREAD

**Issue by e9ab98e991ab** [pengwei1024/LogUtils#57]
com.apkfuns.logutils.Constant: can't find referenced method 'java.util.List getParseList()' in program class com.apkfuns.logutils.LogConfigImpl

**Comment by pengwei1024** [comment]
你说的是no-op版本吧？确实存在找不到方法的情况，我尽快修复下

**Comment by pengwei1024** [comment]
> com.apkfuns.logutils.Constant: can't find referenced method 'java.util.List getParseList()' in program class com.apkfuns.logutils.LogConfigImpl

你是不是调用了ObjectUtil 类方法？按道理说正常情况no-op版本调用不到 `Constant#getParsers()`

**Comment by e9ab98e991ab** [comment]
打正式包的时候报的错，说找不到getParseList（）这个方法 godfeer 邮箱：godfeer@aliyun.com 签名由 网易邮箱大师 定制 在2019年03月08日 19:27，舞影凌风 写道： com.apkfuns.logutils.Constant: can't find referenced method 'java.util.List getParseList()' in program class com.apkfuns.logutils.LogConfigImpl 你是不是调用了ObjectUtil 类方法？按道理说正常情况no-op版本调用不到 Constant#getParsers() — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by pengwei1024** [comment]
> 打正式包的时候报的错，说找不到getParseList（）这个方法 godfeer 邮箱：godfeer@aliyun.com 签名由 网易邮箱大师 定制 在2019年03月08日 19:27，舞影凌风 写道： com.apkfuns.logutils.Constant: can't find referenced method 'java.util.List getParseList()' in program class com.apkfuns.logutils.LogConfigImpl 你是不是调用了ObjectUtil 类方法？按道理说正常情况no-op版本调用不到 Constant#getParsers() — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

1.7.5 版本应该已经没有问题了欢迎试用
