### ISSUE TITLE
文件名出现乱码！

### ISSUE THREAD

**Issue by tomato0127** [pengwei1024/LogUtils#59]
![image](https://user-images.githubusercontent.com/25834632/54353109-34fff200-468e-11e9-8a9d-8ef4519a4510.png)

android 4.3.0 中文，rk3188平台 ，应该是JNI处理文件名的时候出现的问题，麻烦老哥处理一下。

**Comment by pengwei1024** [comment]
> ![image](https://user-images.githubusercontent.com/25834632/54353109-34fff200-468e-11e9-8a9d-8ef4519a4510.png)
> 
> android 4.3.0 中文，rk3188平台 ，应该是JNI处理文件名的时候出现的问题，麻烦老哥处理一下。

试一下1.3.0版本哟，应该解决了
```
implementation 'com.apkfuns.log2file:log2file:1.3.0'
```

**Comment by tomato0127** [comment]
> > ![image](https://user-images.githubusercontent.com/25834632/54353109-34fff200-468e-11e9-8a9d-8ef4519a4510.png)
> > android 4.3.0 中文，rk3188平台 ，应该是JNI处理文件名的时候出现的问题，麻烦老哥处理一下。
> 
> 试一下1.3.0版本哟，应该解决了
> 
> ```
> implementation 'com.apkfuns.log2file:log2file:1.3.0'
> ```
老哥，给力，帅，牛！！
