### ISSUE TITLE
log2file需要加入arm64-v8a的支持

### ISSUE THREAD

**Issue by 0xByteLeon** [pengwei1024/LogUtils#62]
liblog4a-lib.so缺少arm64-v8a的支持，能否增加呢？

**Comment by ShawnXiaFei** [comment]
不缺，在gradle里面加：
```
    sourceSets {
        main {
            jniLibs.srcDirs = ['libs']
        }
    }
```

**Comment by pengwei1024** [comment]
> liblog4a-lib.so缺少arm64-v8a的支持，能否增加呢？

应该是包含了v8a的。可以看gradle 配置 [build.gradle](https://github.com/pengwei1024/LogUtils/blob/master/log2file/build.gradle)   或者 [jcenter](https://jcenter.bintray.com/com/apkfuns/log2file/log2file/1.3.1/)

**Comment by 0xByteLeon** [comment]
似乎是gradle缓存问题，项目代码重新下载导入后问题解决
