### ISSUE TITLE
混淆怎么弄啊，一直报错

### ISSUE THREAD

**Issue by YiuChoi** [pengwei1024/LogUtils#8]
Warning: com.apkfuns.logutils.LogType$LogTypes: can't find referenced class com.apkfuns.logutils.LogType

**Comment by pengwei1024** [comment]
你可以试试加上这个LogUtils就不会混淆了
```
-keep public class com.apkfuns.logutils.*{*;}
```
而且LogType是内部类，你还需要加上这个
```
-keepattributes InnerClasses
```
希望对你的问题有帮助

**Comment by pengwei1024** [comment]
@YiuChoi
